{% set name = "langsmith" %}
{% set version = "0.4.46" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/langsmith-{{ version }}.tar.gz
  sha256: 0b73d47ebd0a27ea10edec1717f36f6a865cb9ffc7f4e6a419e2cea1ab3c5b1e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }},<4.0
    - pydantic >=1,<3
    - requests >=2.0.0
    - orjson >=3.9.14
    - httpx >=0.23.0,<1
    - requests-toolbelt >=1.0.0
    - zstandard >=0.23.0
    - packaging >=23.2
  run_constrained:
    - langsmith-pyo3 >=0.1.0rc2,<0.2.0
    - rich >=13.9.4
    - pytest >=7.0.0
    - openai-agents >=0.0.3,<0.1
    - opentelemetry-sdk >=1.30.0,<2.0.0
    - opentelemetry-api >=1.30.0,<2.0.0
    - opentelemetry-exporter-otlp-proto-http >=1.30.0,<2.0.0

test:
  imports:
    - langsmith
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith LLM Tracing and Evaluation Platform.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/docs/
  dev_url: https://github.com/langchain-ai/langchainplus-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
    - jan-janssen
