{% set name = "langsmith" %}
{% set version = "0.1.57" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/langsmith-{{ version }}.tar.gz
  sha256: 4682204de19f0218029c2b8445ce2cc3485c8d0df9796b31e2ce4c9051fce365

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  entry_points:
    - langsmith = langsmith.cli.main:main

requirements:
  host:
    - python >=3.8.1,<4.0
    - poetry-core
    - pip
  run:
    - python >=3.8.1,<4.0
    - pydantic >=1,<3
    - requests >=2.0.0,<3.0.0
    - orjson >=3.9.14,<4.0.0

test:
  imports:
    - langsmith
    - langsmith.schemas
    - langsmith.client
  commands:
    - pip check
    - langsmith -h
  requires:
    - pip

about:
  home: https://smith.langchain.com/
  summary: Client library to connect to the LangSmith language model tracing and evaluation API.
  description: |
    LangSmith helps you visualize and evaluate language model applications to help you build better
    performing applications. This is the client library to connect to the LangSmith API.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://docs.smith.langchain.com/docs/
  dev_url: https://github.com/langchain-ai/langchainplus-sdk

extra:
  recipe-maintainers:
    - pavelzw
    - hinthornw
    - vowelparrot
